name: Discord Notifications

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"🚀 Nuevo commit de ${{ github.actor }} en develop\"}" \
          "https://discord.com/api/webhooks/1505473610624667772/Rgj9Oz3qnFIi4UMgNX7Q_lOdGO9qZEIumUT5PLJqOZdfV67_Kd348hsyW6y47SXq4FG1"
